apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notification.fullname" . }}
  labels: { app: notification }
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app: notification }
  template:
    metadata:
      labels: { app: notification }
    spec:
      containers:
        - name: notification
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "IfNotPresent" }}
          env:
            - name: RESULT_Q
              value: {{ .Values.env.RESULT_Q | quote }}
            - name: REDIS_URL
              value: {{ .Values.env.REDIS_URL | quote }}
          command: ["python", "-m", "services.notification.main"]
