apiVersion: v2
name: stack
version: 0.1.0
description: Umbrella chart for async-processing demo

dependencies:
  # Upstream infra
  - name: redis
    version: 18.13.2
    repository: https://charts.bitnami.com/bitnami
  - name: rabbitmq
    version: 12.7.1
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    version: 15.5.2
    repository: https://charts.bitnami.com/bitnami
  - name: airflow
    version: 1.16.0
    repository: https://airflow.apache.org
    alias: airflow

  # Local micro-services (directories under charts/)
  - name: api
    version: 0.1.0
    repository: "file://./charts/api"
  - name: consumer
    version: 0.1.0
    repository: "file://./charts/consumer"
  - name: notification
    version: 0.1.0
    repository: "file://./charts/notification"
  - name: frontend
    version: 0.1.0
    repository: "file://./charts/frontend"
